pull_request_rules:
  - name: automatic merge for main when CI passes and 2 reviews
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=Run Jest tests / test (pull_request)
      - base=main
    actions:
      merge:
        method: merge